# Xiaomi Kernel Feature
obj-$(CONFIG_FOCUS_TASK)	+= focus.o
obj-$(CONFIG_MILLET)	+= millet_core.o
obj-$(CONFIG_MILLET)	+= millet_pkg.o
obj-$(CONFIG_MILLET)	+= millet_hs.o
obj-$(CONFIG_XIAOMI_METIS)	+= metis.o
